# Generated by Django 4.1.7 on 2023-03-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfiguration_data', '0003_alter_title_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='input_data',
            field=models.TextField(help_text='100 characters max.'),
        ),
    ]
