# Generated by Django 4.1.7 on 2023-03-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfiguration_data', '0004_alter_data_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='input_data',
            field=models.TextField(),
        ),
    ]
