# Generated by Django 4.1.7 on 2023-03-31 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfiguration_data', '0005_alter_data_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='priority',
            field=models.IntegerField(blank=True, default='', null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
